version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g serverless
      - npm install
  build:
    commands:
      - mkdir -p target/dev
      - mkdir target/prod
      - serverless package --verbose --package target/dev --stage dev -r us-east-1
      - serverless package --verbose --package target/prod --stage prod -r us-east-1

cache:
  paths:
    - node_modules

artifacts:
  files:
    - target/**/*
    - serverless.yml
    - deploy.sh
